### ISSUE TITLE
Can Notary work with replication of images ?

### ISSUE THREAD

**Issue by sahotay** [notaryproject/notary#1280]
Hello Everyone:

I need your suggestion, please!

We have Artifactory(`myownartifactory**A**.sahotay.com`) to store our docker images and replicating some of the images to other Artifactory servers (`myownartifactory**B**.sahotay.com`).

We have signed the images using notary and push the images to `myownartifactory**A**.sahotay.com` , images got replicated to another server i.e. `myownartifactory**B**.sahotay.com` .

A person enabled content Trust cannot pull the image from `myownartifactory**B**.sahotay.com` because it is signed for server A.

Any suggestion to pull replicated images while having content Trust enabled ?

**Comment by HuKeping** [comment]
The trust data was based on GUN, so I think if you could deploy a proxy( **C**.sahotay.com) and signed with this GUN?

**Comment by Rahul-github** [comment]
Thanks @HuKeping for the suggestion but will you please elaborate more how having this proxy can help?

**Comment by HuKeping** [comment]
Since the image you offered is exactly the same except for the severs for storing.  All the backup activities should be transparent to user, what they can see is only the proxy exposed to them.

Once the admin push and sign the image with the name of C.image.name, the notary service will generate the trusted data for C.image.name no matter where it finally be stored( the proxy will choose where to store it).

When the user wants to pull the prior image, since it has already been signed with C.image.name, everything will be fine.

```
                            --------- A  (transparent to consumer )
                          |
consumer ----- C (the consumer should only see and docker pull from C)
                          |
                            --------- B  (transparent to consumer )
```

**Comment by Rahul-github** [comment]
Thanks a lot @HuKeping

**Comment by kfox1111** [comment]
This is a big problem I think. I was just starting to explore notary for container signing, but some of our sites run disconnected and we replicate images in the disconnected environments. Its often better to not have the exact same name internally. Is there any way to sign images by sha rather then by handle? Are there any tools similar to skopeo for replicating signatures?

**Comment by HuKeping** [comment]
> Is there any way to sign images by sha rather then by handle

Notary could sign everything,  but as for your case, you may need something like a proxy or a wrapper to handle the  `sha` to `image name`  and `image name` to `sha`process.

>  but some of our sites run disconnected and we replicate images in the disconnected environments.
BTW, why not using a  reverse proxy  like `Nginx` to  handle these things?
