### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by williamdes** [notaryproject/notary#1601]
Hi !

I just noticed a 0.7 tag is pushed but no release has been written for it, that makes people think that the latest release was in 2018.

Also, why https://docs.docker.com/notary/changelog/ is not up to date ?

**Comment by thaJeztah** [comment]
@justincormack ptal

**Comment by thaJeztah** [comment]
There's some changes in master as well that are not yet in the v0.7.0 release (in case you're planning to tag those https://github.com/theupdateframework/notary/compare/v0.7.0...master)

**Comment by williamdes** [comment]
🏓 anyone ?

**Comment by williamdes** [comment]
@justincormack what do you think?

**Comment by williamdes** [comment]
Nobody cares
