### ISSUE TITLE
Create a .github repo for org readme and governance

### ISSUE THREAD

**Issue by SteveLasker** [notaryproject/notary#1666]
The current [governance documents](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md) are in this `notary` repo for historical reasons.

This issue is to cover:
- [ ] creating a new `.github` repo which will serve as the [org readme contents](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile) when someone navigates to: https://github.com/notaryproject/
- [ ] copy the existing [governance documents](https://github.com/notaryproject/notary/blob/master/GOVERNANCE.md) to this new repo for central visibility

Please add👍 to the comment if you agree with the above

**Comment by justincormack** [comment]
LGTM

**Comment by toddysm** [comment]
This is also a duplicate of https://github.com/notaryproject/roadmap/issues/77

**Comment by toddysm** [comment]
@SteveLasker please check https://github.com/notaryproject/roadmap/issues/77#issuecomment-1414327219. Let's close this issue and track using the other one.

**Comment by SteveLasker** [comment]
Resolved with https://github.com/notaryproject/roadmap/issues/77
